reddit/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only: [:new, :create, :show, :index]
  resource :session, only: [:new, :create, :destroy]

  resources :subs, except: [:destroy] do
    resources :posts,only: [:index]
  end
  resources :posts,except: [:index]
end

reddit/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

reddit/app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id         :bigint           not null, primary key
#  title      :string           not null
#  url        :string
#  content    :text
#  sub_id     :integer          not null
#  author_id  :integer          not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class Post < ApplicationRecord
    validates :title, :sub_id, :author_id, presence: true
    belongs_to(
        :sub,
        class_name: 'Sub', 
        foreign_key: :sub_id
    )
    belongs_to(
        :author,
        class_name: 'User', 
        foreign_key: :author_id
    )
end

reddit/app/models/sub.rb
# == Schema Information
#
# Table name: subs
#
#  id           :bigint           not null, primary key
#  title        :string           not null
#  description  :text             not null
#  moderator_id :integer          not null
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#
class Sub < ApplicationRecord
    validates :title, :description, :moderator_id, presence: true

    belongs_to :moderator,
    class_name: 'User',
    foreign_key: :moderator_id
    has_many(
        :posts,
        class_name: 'Post', 
        foreign_key: :sub_id
    )
end

reddit/app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :bigint           not null, primary key
#  username        :string           not null
#  password_digest :string           not null
#  session_token   :string           not null
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#
class User < ApplicationRecord
    validates :username, presence:true, uniqueness:true
    validates :password_digest, presence:true
    validates :password, length: {minimum:6}, allow_nil:true
    attr_reader :password
    after_initialize :ensure_session_token

    def self.find_by_credentials(username, password)
        user = User.find_by(username: username)
        return nil if user.nil?
        user.is_password?(password) ? user : nil
    end
    def password=(password)
        self.password_digest = BCrypt::Password.create(password)
        @password = password
    end
    def is_password?(password)
        user_object = BCrypt::Password.new(self.password_digest)
        user_object.is_password?(password)
    end
    def reset_session_token!
        self.session_token = SecureRandom::urlsafe_base64
        self.save!
        self.session_token
    end
    def ensure_session_token
        self.session_token ||= SecureRandom::urlsafe_base64
    end

    has_many :subs_moderated,
    class_name: 'Sub',
    foreign_key: :moderator_id

    has_many(
        :posts,
        class_name: 'Post', 
        foreign_key: :author_id
    )
end

reddit/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    helper_method :current_user, :logged_in?
    def current_user
        @current_user ||= User.find_by(session_token: session[:session_token])
    end
    def require_logged_in
        redirect_to new_session_url unless logged_in?
    end
    def require_logged_out
        redirect_to users_url if logged_in?
    end
    def logged_in?
        !!current_user
    end
    def login(user)
        session[:session_token] = user.reset_session_token!
    end
    def logout
        @current_user.reset_session_token! if logged_in?
        session[:session_token] = nil 
        @current_user = nil
    end
end

reddit/app/controllers/posts_controller.rb
class PostsController < ApplicationController
    before_action :require_logged_in, except [:show, :index]
    def edit
        @post ||= Post.find_by(id:params[:id])
        if @post && @post.author_id == @current_user.id
            render :edit
        else
            flash[:errors] = ["This is not your post"]
            redirect_to post_url(@post)
        end
    end
    def update
        if @post.update(post_params)
            redirect_to post_url(@post)
        else
            flash.now[:errors] = @post.errors.full_messages
            render :edit
        end
    end
    def show
        @post = Post.find_by(id: params[:id])
        render :show
    end
    def index
        @posts = Post.where(sub_id:params[:sub_id])
        render :index
    end
    def new
        @post = Post.new
        render :new
    end
    def create
        @post = Post.new(post_params)
        @post.author_id = @current_user.id
        if @post.save
            redirect_to post_url(@post)
        else
            flash.now[:errors] = @post.errors.full_messages
            render :new
        end
    end
    private
    def post_params
        params.require(:post).permit(:title, :url, :content, :sub_id)
    end
end

reddit/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    before_action :require_logged_out, only: [:new, :create]
    before_action :require_logged_in, only: [:destroy]
    def new
        
        render :new
    end
    def create
        @user = User.find_by_credentials(params[:user][:username], params[:user][:password])
        if @user
            login(@user)
            redirect_to user_url(@user)
        else
            flash.now[:errors] = ["invalid username or password"]
            render :new
        end
    end
    def destroy
        logout
        redirect_to new_session_url
    end
end

reddit/app/controllers/subs_controller.rb
class SubsController < ApplicationController
    before_action :require_logged_in, except: [:show, :index]

    def index
        @subs = Sub.all
        render :index
    end

    def show
        @sub = Sub.find_by(id: params[:id])
        render :show
    end

    def edit
        @sub ||= Sub.find_by(id: params[:id])
        if @sub && current_user.id == @sub.moderator_id
            render :edit
        else
            flash[:errors] = ["This is not your sub"]
            redirect_to subs_url
        end
    end

    def update
        if @sub.update(sub_params)
            redirect_to sub_url(@sub)
        else
            flash.now[:errors] = @sub.errors_full_messages
            render :edit
        end
    end
    def new
        @sub = Sub.new
        render :new
    end
    def create
        @sub = Sub.new(sub_params)
        @sub.moderator_id = current_user.id
        if @sub.save
            redirect_to sub_url(@sub)
        else
            flash.now[:errors] = @sub.errors.full_messages
            render :new
        end
    end

    private
    def sub_params
        params.require(:sub).permit(:title, :description)
    end
end

reddit/app/controllers/users_controller.rb
class UsersController < ApplicationController
    # before_action :require_logged_out, only: [:new, :create]
    before_action :require_logged_in, only: [:index, :show]
    def new
        @user = User.new
        render :new
    end
    def create
        @user = User.new(user_params)
        if @user.save
            login(@user)
            redirect_to user_url(@user)
        else
            flash.now[:errors] = @user.errors.full_messages
            render :new
        end
    end
    def show
        @user = User.find(params[:id])
        render :show
    end
    def index
        @users = User.all
        render :index
    end
    private
    def user_params
        params.require(:user).permit(:username, :password)
    end
end

reddit/app/helpers/application_helper.rb
module ApplicationHelper
end

reddit/app/helpers/posts_helper.rb
module PostsHelper
end

reddit/app/helpers/sessions_helper.rb
module SessionsHelper
end

reddit/app/helpers/subs_helper.rb
module SubsHelper
end

reddit/app/helpers/users_helper.rb
module UsersHelper
end

reddit/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Reddit</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if logged_in? %>
      <form action="<%= session_url %>" method="post">
      <input type="hidden" name="_method" value="delete">
      <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
        <input type="submit" value="Logout"> 
      </form>
    <% else %>
      <form action="<%= new_user_url %>" method="get">
      <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
        <input type="submit" value ="Sign Up">
      </form>
    <% end %>


    <%= yield %>
  </body>
</html>

reddit/app/views/subs/edit.html.erb
<h1>This is the subs edit form</h1>

reddit/app/views/subs/index.html.erb
<h1>This is the subs index page</h1>

reddit/app/views/subs/new.html.erb
<h1>Create a Sub</h1>

<form action="<%= subs_url %>" method="POST">
    <input type="hidden" name="authenticity_token" value= <%= form_authenticity_token %>>
    <label>Title
        <input type="text" name="sub[title]" value=<%= @sub.title %>>
    </label>
    <label>Description
        <textarea name="sub[description]" value="<%= @sub.description %>"><%= @sub.description %></textarea>
    </label>
    <input type="submit" value="Create Sub">
</form>

<% if flash[:errors] %>
    <%= flash[:errors] %>
<% end %>

reddit/app/views/subs/show.html.erb
<h1>This is the subs show page</h1>

reddit/app/views/users/index.html.erb
<h1>This is the users index page</h1>

<ul>
    <% @users.each do |user| %>
        <li><%= user.username %></li>
    <% end %>
</ul>

reddit/app/views/users/new.html.erb
<h1>Sign Up</h1>

<form action="<%= users_url %>" method="POST">
    <input type="hidden" name="authenticity_token" value= <%= form_authenticity_token %>>
    <label>Username
        <input type="text" name="user[username]" value=<%= @user.username %>>
    </label>
    <label>Password
        <input type="password" name="user[password]">
    </label>
    <input type="submit" value="Sign Up">
</form>

<% if flash[:errors] %>
    <%= flash[:errors] %>
<% end %>

reddit/app/views/users/show.html.erb
<h1>This is the users show page</h1>